name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: xdebug

      - uses: actions/checkout@v5

      - name: Get Composer cache directory path
        id: composer-cache-dir-path
        run: echo "path=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache-dir-path.outputs.path }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run tests
        run: composer test

      - name: Run code style check
        run: composer phpcs